import re

# List of (regular expression, replacement) pairs for abbreviations in hausa:
abbreviations_ha = [
    (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
    for x in [
        ("wlh", "wallahi"),
        ("isa", "inshaallah"),
        ("slm", "salam"),
        ("aslm", "assalamu alaikum"),
        ("aslm", "assalam alaikum"),
        ("wslm", "wa'alaikumu salam"),
        ("w/slm", "wa'alaikumu salam"),
        ("saw", "salallahu alaihi wasalam"),
        ("as", "alaihi salam"),
        ("sw", "subhanahu wata’allah"),
        ("ra", "radiyallahu anhu"),
        ("ra", "radiyallahu anha"),
        ("alhmd", "alhamdulillah"),
        ("ykk", "yakake"),
        ("ykk", "yakike"),
        ("ngd", "nagode"),
        ("gsky", "gaskiya"),
        ("lfy", "lafiya"),
        ("lpy", "lafiya"),
        ("gdy", "godiya"),
        ("hkr", "hakuri"),
        ("alh", "alhaji"),
        ("haj", "hajiya"),
        ("hkr", "hakuri"),
        ("mal", "mallam"),
        ("mal", "malama"),
        ("srk", "sarki"),
        ("klu", "kalau"),
        ("lbr", "labari"),
        ("lbr", "labarai"),
        ("bb", "babu"),
        ("lit", "litinin"),
        ("lrb", "laraba"),
        ("lhd", "lahadi"),
        ("asb", "asabar"),
        ("tlt", "talata"),
        ("min", "minti"),
        ("kyye", "kiyaye"),
        ("wnn", "wannan"),
        ("y", "ya"),
        ("yy", "yaya"),
        ("lkc", "lokaci"),
        ("lkcn", "lokacin"),
        ("mgn", "magana"),
        ("hk", "haka"),
        ("ahk", "ahaka"),
        ("ynz", "yanzu"),
        ("bbu", "babu"),
        ("dmw", "damuwa"),
        ("bkt", "bukata"),
        ("hausw", "hausawa"),
        ("2rai", "turai"),
        ("2ra", "tura"),
        ("lau", "kalau"),
        ("dftn", "dafatan"),
        ("mgd", "mungode")
    ]
]
